class Language():
    language = 'ru'

    def __init__(self):
        self.title_by_language = {"ru": {"FILE_NOUNS": 'ru_nouns',
                                         "FILE_CHINA_TRANS": 'ru_china_trans',
                                         "TITLE_BTN_NEXT": 'Следующий',
                                         "TITLE_NAME_ONLY_CHARACTERS": 'Имя только из букв',
                                         "TITLE_NAME_NOT_LONGER": 'Имя до 10 символов',
                                         "TITLE_HI_WHAT_ARE_YOUR_NAME": 'Привет! Как тебя зовут?',
                                         "TITLE_HOW_LOD_ARE_YOU": 'какого \nты года рождения?',
                                         "TITLE_YOU_ARE_FROM_THE_PAST": 'Ты из прошлого?',
                                         "TITLE_YOU_ARE_FROM_THE_FUTURE": 'Ты из будущего?',
                                         "TITLE_YOUR_MAIL": 'Твоя электронная почта?',
                                         "TITLE_DONT_LOOK_LIKE_REAL_MAIL": 'На настоящую почту не похоже!',
                                         "TITLE_WHAT_GENDER_ARE_YOU": 'Последний вопрос. \nКакого ты пола?',
                                         "TITLE_MALE": 'Мужской',
                                         "TITLE_FEMALE": 'Женский',
                                         "TITLE_BTN_EXIT": 'Выход',
                                         "TITLE_BTN_SYNCHRONIZE": 'Синхронизировать',
                                         "TITLE_BTN_CHOOSE_LANGUAGE": 'Выбор языка',
                                         "TITLE_BTN_HOW_IT_WORKS": 'Как это работает',
                                         "TITLE_HOME_HEADER_A1": 'Слова уровня А1',
                                         "TITLE_HOME_HEADER_A2": 'Слова уровня А2',
                                         "TITLE_BTN_TOPICS": 'Темы',
                                         "TITLE_HAIR": 'Прошёл',
                                         "TITLE_REPEAT": 'Повторил',
                                         "TITLE_KNOW": 'Запомнил',
                                         "TITLE_NOT_AVAILABLE_SERVER": 'Недоступно',
                                         "TITLE_LOAD_FROM_SERVER": 'Загрузил',
                                         "TITLE_APP_NEED_FOR_HEADER": 'Это программа для подбора образов кодирующих иностранное слово',
                                         "TITLE_APP_NEED_FOR_BLOC1": 'Перевод слова зависит от темы!\nЭтапы подбора образов:\n1) Выбери тему.\n2) Выбери способ разбития слова.\n3) Подбери побходящей тебе образ или введи свой вариант\n4) Если образы не подходят, вернись и разбей слово по другому',
                                         "TITLE_APP_NEED_FOR_BLOC2": '\nЭтапы формирования ассоциаций\n0) Нужно представить мини сценку\n1) Подобрать образы одного размера\n2) Соединить образы в 3D\n3) добавить действие (нелепые, смешные, пошлые)\n4) 6 секунд на детали, добавить (звук, запах, потертости)\n6) глядя вверх 3 раза повторить слово по-английски',
                                         "TITLE_APP_NEED_FOR_BLOC3": 'Для среднестатистического человека наиболее эффективно и реально учить по 5-10 слов в день. Используя мнемотехнику любой человек при желании может выйти на скорость запоминания от 100 слов в час и выше. Но существует кривая забывания:',
                                         "TITLE_APP_NEED_FOR_BLOC4": '\nЧтобы запомнить информацию надолго, после изучения нужно повторять ее минимум пять раз.\n\nКогда повторять\nПовторение с полной расшифровкой. Этот способ применяется для закрепления в памяти только что изученной информации.\nЧерез 20-30 минут после первого изучения;\nЧерез пару часов;\nна следующий день;\nПросмотр опорных образов если надо сохранить информацию, которая не используется больше, чем 1,5 месяца\nЧерез 1-2 недели;\nЧерез 2-3 месяца после четвертого повторения.\nЧерез год',
                                         "TITLE_APP_NEED_FOR_BLOC5": 'Путь мнемотехники в памяти в разное количество повторений',
                                         "TITLE_LANGUAGE_ASSOCIATION": 'С каким языком ассоциировать?',
                                         "TITLE_LANGUAGE_RUSSIAN": 'Русский',
                                         "TITLE_LANGUAGE_UKRAINIAN": 'Украинский',
                                         "TITLE_TOPIC_HEADER": 'Темы и прогресс',
                                         "TITLE_TOPIC_UNBLOCK_CHOOSE_TOPIC": 'Доступная новая тема!',
                                         "TITLE_TOPIC_BTN_ANSWERS": 'Знаю',
                                         "TITLE_TOPIC_BTN_LEARN": 'Учить',
                                         "TITLE_TOPIC_BTN_NEXT": 'Дальше',
                                         "TITLE_REMEMBERING_IMAGINATION": 'Представь выбранные объекты используя тематику!',
                                         "TITLE_REMEMBERING_RESIZE": 'Уменьшить/увеличить объекты до размера баскетбольного мяча.',
                                         "TITLE_REMEMBERING_ACTION": 'Добавить действие (нелепые, смешные, пошлые)',
                                         "TITLE_REMEMBERING_DETAILS": '6 секунд на детали, добавить (звук, запах, потертости)',
                                         "TITLE_REMEMBERING_SPEAK": 'Глядя вверх в голос 3 раза повторить слово по-английски',
                                         "TITLE_REMEMBERING_READY": 'Есть',
                                         "TITLE_TOPIC_BTN_OBJECTS": 'Объекты',
                                         "TITLE_TOPIC_BTN_FORGET": 'Забыл',
                                         "TITLE_TOPIC_BTN_BAD": 'Плохо',
                                         'TITLE_TOP_NAME_TOPIC_TOWN': 'Город',
                                         'TITLE_TOP_NAME_CITY': 'Город',
                                         'TITLE_TOP_NAME_HOME': 'Дом',
                                         'TITLE_TOP_NAME_HOUSE': 'Дом',
                                         'TITLE_TOP_NAME_FOOD': 'Еда',
                                         'TITLE_TOP_NAME_NATURE': 'Природа',
                                         'TITLE_TOP_NAME_HUMAN': 'Человек',
                                         'TITLE_TOP_NAME_RELATIONS': 'Отношения',
                                         'TITLE_TOP_NAME_VEHICLE': 'Транспорт',
                                         'TITLE_TOP_NAME_TRANSPORT': 'Транспорт',
                                         'TITLE_TOP_NAME_ANIMALS': 'Животные',
                                         'TITLE_TOP_NAME_SPORT': 'Спорт',
                                         'TITLE_TOP_NAME_COLORS': 'Цвета',
                                         'TITLE_TOP_NAME_WORK': 'Работа',
                                         'TITLE_TOP_NAME_PROFESSIONS': 'Профессии',
                                         'TITLE_TOP_NAME_SCHOOL': 'Изучение',
                                         'TITLE_TOP_NAME_LEARNING': 'Изучение',
                                         'TITLE_TOP_NAME_ENTERTAINMENT': 'Развлечения',
                                         'TITLE_TOP_NAME_CLOCK': 'Время',
                                         'TITLE_TOP_NAME_CALENDAR': 'Календарь',
                                         'TITLE_TOP_NAME_CLOTHING': 'Одежда',
                                         'TITLE_TOP_NAME_HOBBY': 'Хобби',
                                         'TITLE_TOP_NAME_MOVIE': 'Кино',
                                         'TITLE_TOP_NAME_WAR': 'Война',
                                         'TITLE_TOP_NAME_INTERNET': 'Интернет',
                                         'TITLE_TOP_NAME_COMMERCE': 'Коммерция',
                                         'TITLE_TOP_NAME_JUSTICE': 'Правосудие',
                                         'TITLE_TOP_NAME_TECHNIQUE': 'Техника',
                                         'TITLE_TOP_NAME_TRAVEL': 'Путешествие',
                                         'TITLE_TOP_NAME_MEDICINE': 'Медицина',
                                         'TITLE_TOP_NAME_HOUSEHOLD': 'Хозяйство',
                                         'TITLE_TOP_NAME_OTHER': 'Другое',
                                         'TITLE_TOP_NAME_POINTERS': 'Указатели',
                                         'TITLE_TOP_NAME_EXCLAMATION': 'Восклицание',
                                         'TITLE_TOP_NAME_UNIONS': 'союзы',
                                         'TITLE_TOP_NAME_NUMBERS': 'числа',
                                         'TITLE_TOP_NAME_PREPOSITION': 'Предлоги',
                                         'TITLE_TOP_NAME_ADVERB': 'Наречие',
                                         'TITLE_TOP_NAME_AVAILABILITY': 'Наличия',
                                         'TITLE_TOP_NAME_OPERATIONS': 'Операции',
                                         'TITLE_TOP_NAME_COMMUNICATION': 'Общения',
                                         'TITLE_TOP_NAME_STAGES': 'Стадии',
                                         'TITLE_TOP_NAME_MOVEMENTS': 'Движения',
                                         'TITLE_TOP_NAME_THINKING': 'Мышления',
                                         'TITLE_TOP_NAME_OTHER_VERBS': 'Другие глаголы',
                                         'TITLE_TOP_NAME_EMOTIONS': 'Эмоции',
                                         'TITLE_TOP_NAME_ABSTRACT': 'Абстрактные',
                                         'TITLE_TOP_NAME_APPROXIMATELY': 'На глаз',
                                         'TITLE_TOP_NAME_CONDITION': 'Состояние',
                                         'TITLE_TOP_NAME_QUALITIES': 'Качества',
                                         'TITLE_TOP_NAME_PRONOUNS': 'Местоимения',
                                         'TITLE_TOP_NAME_KITCHEN': 'Кухня',
                                         'TITLE_ALERT_REPEAT_COUNT_TOPICS': 'Нужно повторить {} темы!',
                                         'TITLE_TOPIC_NAME_REPEAT': 'Повторить',
                                         'TITLE_TOPIC_NAME_HEARD': 'Прошёл',
                                         'TITLE_TOPIC_NAME_LEARN': 'Выучил',

                                         },

                                  "ua": {"FILE_NOUNS": 'ua_nouns',
                                         "TITLE_TOP_NAME_CITY": 'Місто',
                                         "TITLE_TOP_NAME_HOUSE": 'Будинок',
                                         "TITLE_TOP_NAME_TRANSPORT": 'Транспорт',
                                         "TITLE_TOP_NAME_SCHOOL": 'Вивчення',
                                         "TITLE_TOP_NAME_MOVIE": 'Кіно',
                                         "TITLE_TOP_NAME_WAR": 'Війна',
                                         "TITLE_TOP_NAME_INTERNET": 'Інтернет',
                                         "TITLE_TOP_NAME_COMMERCE": 'Комерція',
                                         "TITLE_TOP_NAME_JUSTICE": 'Правосуддя',
                                         "TITLE_TOP_NAME_TECHNIQUE": 'Техніка',
                                         "TITLE_TOP_NAME_TRAVEL": 'Подорож',
                                         "TITLE_TOP_NAME_MEDICINE": 'Медицина',
                                         "TITLE_TOP_NAME_HOUSEHOLD": 'Господарство',
                                         "TITLE_TOP_NAME_KITCHEN": 'Кухня',
                                         "FILE_CHINA_TRANS": 'ua_china_trans',
                                         "TITLE_BTN_NEXT": 'Наступний',
                                         "TITLE_NAME_ONLY_CHARACTERS": "Ім'я тільки з букв",
                                         "TITLE_NAME_NOT_LONGER": "Ім'я до 10 символів",
                                         "TITLE_HI_WHAT_ARE_YOUR_NAME": 'Вітаю! Як тебе звати?',
                                         "TITLE_HOW_LOD_ARE_YOU": 'якого \nти року народження?',
                                         "TITLE_YOU_ARE_FROM_THE_PAST": 'Ти з минулого?',
                                         "TITLE_YOU_ARE_FROM_THE_FUTURE": 'Ти з майбутнього?',
                                         "TITLE_YOUR_MAIL": 'Твоя електронна пошта?',
                                         "TITLE_DONT_LOOK_LIKE_REAL_MAIL": 'На справжню пошту не схоже!',
                                         "TITLE_WHAT_GENDER_ARE_YOU": 'Останнє питання. \nЯкої ти статі?',
                                         "TITLE_MALE": 'Чоловічий',
                                         "TITLE_FEMALE": 'Жіночий',
                                         "TITLE_APP_NEED_FOR_HEADER": 'Це програма для підбору образів, що кодують іноземне слово',
                                         "TITLE_BTN_EXIT": 'Вихід',
                                         "TITLE_BTN_SYNCHRONIZE": 'синхронізувати',
                                         "TITLE_BTN_CHOOSE_LANGUAGE": 'Вибір мови',
                                         "TITLE_BTN_HOW_IT_WORKS": 'Як це працює',
                                         "TITLE_HOME_HEADER_A1": 'Слова рівня А1',
                                         "TITLE_HOME_HEADER_A2": 'Слова рівня А2',
                                         "TITLE_BTN_TOPICS": 'Теми',
                                         "TITLE_HAIR": 'Пройшов',
                                         "TITLE_REPEAT": 'Повторив',
                                         "TITLE_KNOW": 'Запам\'ятав',
                                         "TITLE_NOT_AVAILABLE_SERVER": 'Недоступний',
                                         "TITLE_LOAD_FROM_SERVER": 'Завантажив',
                                         "TITLE_APP_NEED_FOR_BLOC1": 'Переклад слова залежить від теми!\nЕтапи підбору образів:\n1) Вибери тему.\n2) Вибери спосіб розбиття слова.\n3) Підбери образ, що тобі походить, або введи свій варіант\n4) Якщо образи не підходять, повернися і розбий слово по іншому',
                                         "TITLE_APP_NEED_FOR_BLOC2": '\nЕтапи формування асоціацій\n0) Потрібно уявити міні сценку\n1) Підібрати образи одного розміру\n2) Поєднати образи в 3D\n3) додати дію (безглузді, смішні, вульгарні)\n4) 6 секунд на деталі, додати (звук, запах, потертості)\n6) дивлячись вгору 3 рази повторити слово англійською',
                                         "TITLE_APP_NEED_FOR_BLOC3": 'Для середньої людини найбільш ефективно і реально вчити по 5-10 слів на день. Використовуючи мнемотехніку, будь-яка людина при бажанні може вийти на швидкість запам\'ятовування від 100 слів на годину і вище. Але існує крива забування: ',
                                         "TITLE_APP_NEED_FOR_BLOC4": '\nЩоб запам\'ятати інформацію надовго, після вивчення потрібно повторювати її мінімум п\'ять разів.\n\nКоли повторювати\nПовторення з повним розшифруванням. Цей спосіб застосовується для закріплення в пам\'яті щойно вивченої інформації.\nЧерез 20-30 хвилин після першого вивчення;\nЧерез пару годин;\nнаступного дня;\nПерегляд опорних образів якщо потрібно зберегти інформацію, яка не використовується більше, ніж 1,5 місяця\nЧерез 1-2 тижні;\nЧерез 2-3 місяці після четвертого повторення.\nЧерез рік',
                                         "TITLE_APP_NEED_FOR_BLOC5": 'Шлях мнемотехніки в пам\'яті в різну кількість повторень',
                                         "TITLE_LANGUAGE_ASSOCIATION": 'З якою мовою асоціювати?',
                                         "TITLE_LANGUAGE_RUSSIAN": 'Російська',
                                         "TITLE_LANGUAGE_UKRAINIAN": 'Український',
                                         "TITLE_TOPIC_HEADER": 'Теми та прогрес',
                                         "TITLE_TOPIC_UNBLOCK_CHOOSE_TOPIC": 'Доступна нова тема!',
                                         "TITLE_TOPIC_BTN_ANSWERS": 'Знаю',
                                         "TITLE_TOPIC_BTN_LEARN": 'Вчити',
                                         "TITLE_TOPIC_BTN_NEXT": 'Далі',
                                         "TITLE_REMEMBERING_IMAGINATION": 'Уяви вибрані об\'єкти використовуючи тематику!',
                                         "TITLE_REMEMBERING_RESIZE": 'Зменшити/збільшити об\'єкти до розміру баскетбольного м\'яча.',
                                         "TITLE_REMEMBERING_ACTION": 'Додати дію (безглузду, смішну, вульгарну)',
                                         "TITLE_REMEMBERING_DETAILS": '6 секунд на деталі, додати (звук, запах, потертості)',
                                         "TITLE_REMEMBERING_SPEAK": 'Дивлячись вгору в голос 3 рази повторити слово англійською',
                                         "TITLE_REMEMBERING_READY": 'Готово',
                                         "TITLE_TOPIC_BTN_OBJECTS": 'Об\'єкти',
                                         "TITLE_TOPIC_BTN_FORGET": 'Забув',
                                         "TITLE_TOPIC_BTN_BAD": 'Погано',
                                         'TITLE_TOP_NAME_TOPIC_TOWN': 'Місто',
                                         'TITLE_TOP_NAME_HOME': 'Будинок',
                                         'TITLE_TOP_NAME_FOOD': 'Їжа',
                                         'TITLE_TOP_NAME_NATURE': 'Природа',
                                         'TITLE_TOP_NAME_HUMAN': 'Людина',
                                         'TITLE_TOP_NAME_RELATIONS': 'Відносини',
                                         'TITLE_TOP_NAME_VEHICLE': 'Транспорт',
                                         'TITLE_TOP_NAME_ANIMALS': 'Тварини',
                                         'TITLE_TOP_NAME_SPORT': 'Спорт',
                                         'TITLE_TOP_NAME_COLORS': 'Кольори',
                                         'TITLE_TOP_NAME_WORK': 'Робота',
                                         'TITLE_TOP_NAME_PROFESSIONS': 'Професії',
                                         'TITLE_TOP_NAME_LEARNING': 'Вивчення',
                                         'TITLE_TOP_NAME_ENTERTAINMENT': 'Розваги',
                                         'TITLE_TOP_NAME_CLOCK': 'Час',
                                         'TITLE_TOP_NAME_CALENDAR': 'Календар',
                                         'TITLE_TOP_NAME_CLOTHING': 'Одяг',
                                         'TITLE_TOP_NAME_HOBBY': 'Хоббі',
                                         'TITLE_TOP_NAME_OTHER': 'Інше',
                                         'TITLE_TOP_NAME_POINTERS': 'Вказiвники ',
                                         'TITLE_TOP_NAME_EXCLAMATION': 'Виклик',
                                         'TITLE_TOP_NAME_UNIONS': 'сполучники',
                                         'TITLE_TOP_NAME_NUMBERS': 'числа',
                                         'TITLE_TOP_NAME_PREPOSITION': 'Прийменник',
                                         'TITLE_TOP_NAME_ADVERB': 'Прислівник',
                                         'TITLE_TOP_NAME_AVAILABILITY': 'Наявності',
                                         'TITLE_TOP_NAME_OPERATIONS': 'Операції',
                                         'TITLE_TOP_NAME_COMMUNICATION': 'Спілкування',
                                         'TITLE_TOP_NAME_STAGES': 'Стадії',
                                         'TITLE_TOP_NAME_MOVEMENTS': 'Рух',
                                         'TITLE_TOP_NAME_THINKING': 'Мислення',
                                         'TITLE_TOP_NAME_OTHER_VERBS': 'Інші дієслова',
                                         'TITLE_TOP_NAME_EMOTIONS': 'Абстрактні',
                                         'TITLE_TOP_NAME_ABSTRACT': 'Емоції',
                                         'TITLE_TOP_NAME_APPROXIMATELY': 'На око',
                                         'TITLE_TOP_NAME_CONDITION': 'Стан',
                                         'TITLE_TOP_NAME_QUALITIES': 'Якості',
                                         'TITLE_TOP_NAME_PRONOUNS': 'Займенники',
                                         'TITLE_ALERT_REPEAT_COUNT_TOPICS': 'Потрібно повторити {} теми!',
                                         'TITLE_TOPIC_NAME_REPEAT': 'Повторити',
                                         'TITLE_TOPIC_NAME_HEARD': 'Пройшов',
                                         'TITLE_TOPIC_NAME_LEARN': 'Вивчив',

                                         },
                                  }

    def set_lang(self, lang):
        self.language = lang

    def title(self, title):
        return self.title_by_language[self.language][title]


if __name__ == '__main__':
    lang = Language()
    name_list = {}
    old_lang_name = ''
    for lang_name in lang.title_by_language.keys():
        if name_list == {}:
            name_list[lang_name] = {}
            old_lang_name = lang_name
            for name in lang.title_by_language[lang_name].keys():
                name_list[lang_name][name] = ''
        else:
            for name in lang.title_by_language[lang_name].keys():
                if name not in name_list[old_lang_name]:
                    print(name)
                else:
                    name_list[old_lang_name][name] = '+'
    for name in name_list[old_lang_name]:
        if name_list[old_lang_name][name] != '+':
            print(name, ':', name_list[old_lang_name][name])
