class Language():
    language = 'ru'

    def __init__(self):
        self.title_by_language = {"ru": {"TITLE_BTN_NEXT": 'Следующий',
                                         "TITLE_NAME_ONLY_CHARACTERS": 'Имя только из букв',
                                         "TITLE_NAME_NOT_LONGER": 'Имя до 10 символов',
                                         "TITLE_HI_WHAT_ARE_YOUR_NAME": 'Привет! Как тебя зовут?',
                                         "TITLE_HOW_LOD_ARE_YOU": 'какого \nты года рождения?',
                                         "TITLE_YOU_ARE_FROM_THE_PAST": 'Ты из прошлого?',
                                         "TITLE_YOU_ARE_FROM_THE_FUTURE": 'Ты из будущего?',
                                         "TITLE_YOUR_MAIL": 'Твоя электронная почта?',
                                         "TITLE_DONT_LOOK_LIKE_REAL_MAIL": 'На настоящую почту не похоже!',
                                         "TITLE_WHAT_GENDER_ARE_YOU": 'Последний вопрос. \nКакого ты пола?',
                                         "TITLE_MALE": 'Мужской',
                                         "TITLE_FEMALE": 'Женский',
                                         "TITLE_BTN_EXIT": 'Выход',
                                         "TITLE_BTN_CHOOSE_LANGUAGE": 'Выбор языка',
                                         "TITLE_BTN_HOW_IT_WORKS": 'Как это работает',
                                         "TITLE_HOME_HEADER": 'Слова уровня А1',
                                         "TITLE_BTN_TOPICS": 'Темы',
                                         "TITLE_HAIR": 'Прошёл',
                                         "TITLE_REPEAT": 'Повторил',
                                         "TITLE_KNOW": 'Запомнил',
                                         "TITLE_APP_NEED_FOR_HEADER": 'Это программа для подбора образов кодирующих иностранное слово',
                                         "TITLE_APP_NEED_FOR_BLOC1": '1) Выбери тему.\n2) Выбери способ разбития слова.\n3) Подбери побходящей тебе образ или введи свой вариант\n4) Если образы не подходят, вернись и разбей слово по другому',
                                         "TITLE_APP_NEED_FOR_BLOC2": '\n Этапы формирования ассоциаций\n 1) Подобрать образы одного размера\n 2) Соединить образы в 3D\n 3) добавить действие (нелепые, смешные, пошлые)\n 4) 6 секунд на детали, добавить (звук, запах, потертости)\n 6) глядя вверх 3 раза повторить слово по-английски',
                                         "TITLE_APP_NEED_FOR_BLOC3": 'Для среднестатистического человека наиболее эффективно и реально учить по 5-10 слов в день. Используя мнемотехнику любой человек при желании может выйти на скорость запоминания от 100 слов в час и выше. Но существует кривая забывания:',
                                         "TITLE_APP_NEED_FOR_BLOC4": '\n Чтобы запомнить информацию надолго, после изучения нужно повторять ее минимум пять раз.\n\n Когда повторять\n Повторение с полной расшифровкой. Этот способ применяется для закрепления в памяти только что изученной информации.\n   Через 20-30 минут после первого изучения;\n   Через пару часов;\n   на следующий день;\n Просмотр опорных образов если надо сохранить информацию, которая не используется больше, чем 1,5 месяца\n   Через 1-2 недели;\n   Через 2-3 месяца после четвертого повторения.\n   Через год',
                                         "TITLE_APP_NEED_FOR_BLOC5": 'Путь мнемотехники в памяти в разное количество повторений',
                                         "TITLE_LANGUAGE_ASSOCIATION": 'С каким языком ассоциировать?',
                                         "TITLE_LANGUAGE_RUSSIAN": 'Русский',
                                         "TITLE_LANGUAGE_UKRAINIAN": 'Украинский',
                                         "TITLE_TOPIC_HEADER": 'Темы и прогресс',
                                         "TITLE_TOPIC_UNBLOCK_CHOOSE_TOPIC": 'Доступная новая тема!',
                                         "TITLE_TOPIC_BTN_ANSWERS": 'Ответы',
                                         "TITLE_TOPIC_BTN_LEARN": 'Учить',
                                         "TITLE_TOPIC_BTN_NEXT": 'Дальше',
                                         "TITLE_REMEMBERING_IMAGINATION": 'Представь выбранные объекты!',
                                         "TITLE_REMEMBERING_RESIZE": 'Уменьшить/увеличить объекты до размера баскетбольного мяча.',
                                         "TITLE_REMEMBERING_ACTION": 'Добавить действие (нелепые, смешные, пошлые)',
                                         "TITLE_REMEMBERING_DETAILS": '6 секунд на детали, добавить (звук, запах, потертости)',
                                         "TITLE_REMEMBERING_SPEAK": 'Глядя вверх 3 раза повторить слово по-английски',
                                         "TITLE_REMEMBERING_READY": 'Есть',
                                         "TITLE_TOPIC_BTN_OBJECTS": 'Объекты',
                                         "TITLE_TOPIC_BTN_FORGET": 'Забыл',
                                         "TITLE_TOPIC_BTN_BAD": 'Плохо',
                                         },

                                  "ua": {"TITLE_BTN_NEXT": 'Наступний',
                                         "TITLE_NAME_ONLY_CHARACTERS": "Ім'я тільки з букв",
                                         "TITLE_NAME_NOT_LONGER": "Ім'я до 10 символів",
                                         "TITLE_HI_WHAT_ARE_YOUR_NAME": 'Вітаю! Як тебе звати?',
                                         "TITLE_HOW_LOD_ARE_YOU": 'якого \nти року народження?',
                                         "TITLE_YOU_ARE_FROM_THE_PAST": 'Ти з минулого?',
                                         "TITLE_YOU_ARE_FROM_THE_FUTURE": 'Ти з майбутнього?',
                                         "TITLE_YOUR_MAIL": 'Твоя електронна пошта?',
                                         "TITLE_DONT_LOOK_LIKE_REAL_MAIL": 'На справжню пошту не схоже!',
                                         "TITLE_WHAT_GENDER_ARE_YOU": 'Останнє питання. \nЯкої ти статі?',
                                         "TITLE_MALE": 'Чоловічий',
                                         "TITLE_FEMALE": 'Жіночий',
                                         "TITLE_APP_NEED_FOR_HEADER": 'Це програма для підбору образів, що кодують іноземне слово',
                                         "TITLE_BTN_EXIT": 'Вихід',
                                         "TITLE_BTN_CHOOSE_LANGUAGE": 'Вибір мови',
                                         "TITLE_BTN_HOW_IT_WORKS": 'Як це працює',
                                         "TITLE_HOME_HEADER": 'Слова рівня А1',
                                         "TITLE_BTN_TOPICS": 'Теми',
                                         "TITLE_HAIR": 'Пройшов',
                                         "TITLE_REPEAT": 'Повторив',
                                         "TITLE_KNOW": 'Запам\'ятав',
                                         "TITLE_APP_NEED_FOR_BLOC1": '1) Вибери тему.\n2) Вибери спосіб розбиття слова.\n3) Підбери образ, що тобі походить, або введи свій варіант\n4) Якщо образи не підходять, повернися і розбий слово по іншому',
                                         "TITLE_APP_NEED_FOR_BLOC2": '\n Етапи формування асоціацій\n 1) Підібрати образи одного розміру\n 2) Поєднати образи в 3D\n 3) додати дію (безглузді, смішні, вульгарні)\n 4) 6 секунд на деталі, додати (звук, запах, потертості)\n 6) дивлячись вгору 3 рази повторити слово англійською',
                                         "TITLE_APP_NEED_FOR_BLOC3": 'Для середньої людини найбільш ефективно і реально вчити по 5-10 слів на день. Використовуючи мнемотехніку, будь-яка людина при бажанні може вийти на швидкість запам\'ятовування від 100 слів на годину і вище. Але існує крива забування: ',
                                         "TITLE_APP_NEED_FOR_BLOC4": '\n Щоб запам\'ятати інформацію надовго, після вивчення потрібно повторювати її мінімум п\'ять разів.\n\n Коли повторювати\n Повторення з повним розшифруванням. Цей спосіб застосовується для закріплення в пам\'яті щойно вивченої інформації.\n Через 20-30 хвилин після першого вивчення;\n Через пару годин;\n наступного дня;\n Перегляд опорних образів якщо потрібно зберегти інформацію, яка не використовується більше, ніж 1,5 місяця\n Через 1-2 тижні;\n Через 2-3 місяці після четвертого повторення.\n Через рік',
                                         "TITLE_APP_NEED_FOR_BLOC5": 'Шлях мнемотехніки в пам\'яті в різну кількість повторень',
                                         "TITLE_LANGUAGE_ASSOCIATION": 'З якою мовою асоціювати?',
                                         "TITLE_LANGUAGE_RUSSIAN": 'Російська',
                                         "TITLE_LANGUAGE_UKRAINIAN": 'Український',
                                         "TITLE_TOPIC_HEADER": 'Теми та прогрес',
                                         "TITLE_TOPIC_UNBLOCK_CHOOSE_TOPIC": 'Доступна нова тема!',
                                         "TITLE_TOPIC_BTN_ANSWERS": 'Відповіді',
                                         "TITLE_TOPIC_BTN_LEARN": 'Вчити',
                                         "TITLE_TOPIC_BTN_NEXT": 'Далі',
                                         "TITLE_REMEMBERING_IMAGINATION": 'Уяви вибрані об\'єкти!',
                                         "TITLE_REMEMBERING_RESIZE": 'Зменшити/збільшити об\'єкти до розміру баскетбольного м\'яча.',
                                         "TITLE_REMEMBERING_ACTION": 'Додати дію (безглузду, смішну, вульгарну)',
                                         "TITLE_REMEMBERING_DETAILS": '6 секунд на деталі, додати (звук, запах, потертості)',
                                         "TITLE_REMEMBERING_SPEAK": 'Дивлячись вгору 3 рази повторити слово англійською',
                                         "TITLE_REMEMBERING_READY": 'Готово',
                                         "TITLE_TOPIC_BTN_OBJECTS": 'Об\'єкти',
                                         "TITLE_TOPIC_BTN_FORGET": 'Забув',
                                         "TITLE_TOPIC_BTN_BAD": 'Погано',
                                         },
                                  }

    def set_lang(self, lang):
        self.language = lang

    def title(self, title):
        return self.title_by_language[self.language][title]


{'know_pr': 0.12, 'repeat_pr': 0.12, 'hair_pr': 1.5, 'time_to_repeat': 1652945705.8, 'etch_top_word': {
    'animal': {'cont_repeat': 0, 'last_word_connect': 1652944508, 'ans_speed': 64, 'objects': ['гЕНИй', 'МЕд'],
               'word_split': ['эни', 'мэл']}, 'elephant': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
    'horse': {'cont_repeat': 0, 'last_word_connect': 1652944509, 'ans_speed': 64, 'objects': ['уХО', 'ОЗеро'],
              'word_split': ['хо', 'ос']},
    'lion': {'cont_repeat': 0, 'last_word_connect': 1652944508, 'ans_speed': 64, 'objects': ['ЛАпа', 'чИН'],
             'word_split': ['ла', 'иэн']},
    'mouse': {'cont_repeat': 0, 'last_word_connect': 1652944507, 'ans_speed': 64, 'objects': ['УС'],
              'word_split': ['маус']},
    'pig': {'cont_repeat': 0, 'last_word_connect': 1652944508, 'ans_speed': 64, 'objects': ['ИГла'],
            'word_split': ['пиг']},
    'bird': {'cont_repeat': 0, 'last_word_connect': 1652944508, 'ans_speed': 64, 'objects': ['БЕДа'],
             'word_split': ['бэд']}, 'kind': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
    'sheep': {'cont_repeat': 5, 'last_word_connect': 1652944507, 'ans_speed': 0},
    'fish': {'cont_repeat': 0, 'last_word_connect': 1652944509, 'ans_speed': 64, 'objects': ['ВИд'],
             'word_split': ['фиш']}, 'snake': {'cont_repeat': 5, 'last_word_connect': 1652944508, 'ans_speed': 0},
    'cat': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
    'chicken': {'cont_repeat': 0, 'last_word_connect': 1652944509, 'ans_speed': 64, 'objects': ['ЧИн', 'КИНо'],
                'word_split': ['чи', 'кин']},
    'cow': {'cont_repeat': 0, 'last_word_connect': 1652944509, 'ans_speed': 64, 'objects': ['КАдр'],
            'word_split': ['кау']},
    'dog': {'cont_repeat': 0, 'last_word_connect': 1652944508, 'ans_speed': 64, 'objects': ['ДОлГ'],
            'word_split': ['дог']}, 'farm': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64}}}

{'know_pr': 0.06, 'repeat_pr': 0.06, 'hair_pr': 0.06, 'time_to_repeat': 1684480507,
 'etch_top_word': {'animal': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'elephant': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'horse': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'lion': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'mouse': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'pig': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'bird': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'kind': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'sheep': {'cont_repeat': 5, 'last_word_connect': 1652944507, 'ans_speed': 0},
                   'fish': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'snake': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'cat': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'chicken': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'cow': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'dog': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64},
                   'farm': {'cont_repeat': 0, 'last_word_connect': 0, 'ans_speed': 64}}}
